import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal.module.css";

export const metadata: Metadata = { title: "Privacy Policy | PENREC Music Group", description: "How PENREC Music Group collects, uses and protects personal information." };

export default function PrivacyPage(){return <main id="content" className={styles.page}>
  <header className={`shell ${styles.hero}`}><p className="eyebrow">Legal / Last updated 4 August 2026</p><h1>Privacy <em>policy.</em></h1><p>This notice explains what personal information PENREC Music Group collects, why we use it and the choices available to you.</p></header>
  <div className={`shell ${styles.layout}`}>
    <nav className={styles.nav} aria-label="Privacy policy sections"><a href="#who">Who we are</a><a href="#collect">Information collected</a><a href="#use">How we use it</a><a href="#sharing">Who receives it</a><a href="#retention">Retention</a><a href="#rights">Your rights</a><a href="#contact">Contact and complaints</a></nav>
    <article className={styles.content}>
      <section id="who"><h2>1. Who we are</h2><p>PENREC Music Group is an independent music project founded and operated by Darren Penman. For UK data-protection purposes, PENREC Music Group is the controller of personal information collected through this website.</p><p>You can contact us about privacy through the <Link href="/contact">PENREC contact form</Link>. Choose “Website support” and include “Privacy” in the subject.</p></section>
      <section id="collect"><h2>2. Information we collect</h2><h3>Contact enquiries</h3><p>When you contact us, we collect your name, email address, enquiry type, subject and message.</p><h3>PENREC accounts</h3><p>If you create an account, we collect your email address, display name, encrypted authentication information and account preferences. Depending on the services you use, we may also store wishlist items, music-library entries and order records.</p><h3>Technical information</h3><p>Our hosting and security providers may process limited technical information such as IP address, browser type, device information, requested pages, timestamps and security logs. Essential authentication cookies are used when you sign in.</p><h3>Information you choose to provide</h3><p>Please do not include sensitive personal information in free-text messages unless it is necessary for your enquiry.</p></section>
      <section id="use"><h2>3. How and why we use information</h2><table className={styles.table}><thead><tr><th>Purpose</th><th>Information</th><th>Lawful basis</th></tr></thead><tbody><tr><td>Responding to enquiries</td><td>Contact details and message</td><td>Legitimate interests in communicating about PENREC and, where relevant, steps requested before a contract</td></tr><tr><td>Creating and securing accounts</td><td>Account and authentication details</td><td>Performance of our agreement with you and legitimate interests in service security</td></tr><tr><td>Providing wishlists, libraries and account preferences</td><td>Account activity and choices</td><td>Performance of our agreement with you</td></tr><tr><td>Managing future purchases and records</td><td>Order, account and transaction records</td><td>Performance of a contract and compliance with legal obligations</td></tr><tr><td>Protecting and improving the website</td><td>Technical and security information</td><td>Legitimate interests in operating a reliable and secure service</td></tr><tr><td>Optional news and release updates</td><td>Email address and communication preferences</td><td>Consent, where you have actively opted in</td></tr></tbody></table><p>We do not sell personal information and we do not use it for automated decision-making or profiling that produces legal or similarly significant effects.</p></section>
      <section id="sharing"><h2>4. Who receives your information</h2><p>We share information only where necessary to operate PENREC, fulfil a request or comply with law. Relevant providers currently include:</p><ul><li><strong>Supabase</strong>, for authentication, database and account services.</li><li><strong>Vercel</strong>, for website hosting, delivery and operational security.</li><li><strong>An email-delivery provider</strong>, when contact-form forwarding is activated.</li><li>Professional advisers, regulators, courts or law-enforcement bodies where disclosure is required or legally justified.</li></ul><p>Some providers may process information outside the UK. Where this happens, we expect appropriate safeguards recognised by UK data-protection law to be used.</p></section>
      <section id="retention"><h2>5. How long we keep information</h2><ul><li>Contact enquiries are normally retained for up to <strong>24 months</strong> after the last meaningful contact, unless a longer period is needed for an ongoing matter.</li><li>Account information is retained while the account remains active and then deleted or anonymised when no longer needed, subject to legal and security requirements.</li><li>Order and financial records may be retained for up to <strong>six years</strong> where required for tax, accounting, dispute or legal purposes.</li><li>Security and technical records are retained only for as long as reasonably necessary for security, diagnosis and legal compliance.</li></ul></section>
      <section id="security"><h2>6. Security</h2><p>We use proportionate technical and organisational safeguards, including restricted database access, row-level security, encrypted connections and HTTP-only authentication cookies. No online service can guarantee absolute security, but we review the controls used to protect PENREC information.</p></section>
      <section id="rights"><h2>7. Your data-protection rights</h2><p>Depending on the circumstances, UK data-protection law may give you rights to:</p><ul><li>request access to your personal information;</li><li>have inaccurate or incomplete information corrected;</li><li>request erasure or restriction of processing;</li><li>object to processing based on legitimate interests;</li><li>receive certain information in a portable format; and</li><li>withdraw consent at any time where consent is the basis used.</li></ul><div className={styles.callout}><p><strong>Your right to object:</strong> you may object to our use of personal information where we rely on legitimate interests. You have an absolute right to object to direct marketing.</p></div><p>These rights are not absolute in every situation. We may need to confirm your identity before acting on a request.</p></section>
      <section id="children"><h2>8. Children</h2><p>The PENREC website and account services are not directed at children under 13. We do not knowingly seek to collect personal information from children under that age.</p></section>
      <section id="contact"><h2>9. Contact and complaints</h2><p>Contact us through the <Link href="/contact">PENREC contact page</Link> to make a request or raise a privacy concern. We will try to resolve concerns directly.</p><p>You also have the right to complain to the UK Information Commissioner’s Office. Information is available at <a href="https://ico.org.uk/make-a-complaint/" rel="noreferrer">ico.org.uk/make-a-complaint</a>.</p></section>
      <section><h2>10. Changes to this notice</h2><p>We may update this policy when PENREC services, providers or legal obligations change. The latest version and its update date will always appear on this page.</p></section>
    </article>
  </div>
</main>}
