import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal.module.css";

export const metadata: Metadata = { title: "Terms of Use | PENREC Music Group", description: "Terms governing use of the PENREC Music Group website and account services." };

export default function TermsPage(){return <main id="content" className={styles.page}>
  <header className={`shell ${styles.hero}`}><p className="eyebrow">Legal / Last updated 4 August 2026</p><h1>Terms of <em>use.</em></h1><p>These terms govern your use of the PENREC Music Group website, music player, catalogue and account services.</p></header>
  <div className={`shell ${styles.layout}`}>
    <nav className={styles.nav} aria-label="Terms sections"><a href="#agreement">Agreement</a><a href="#content">Music and content</a><a href="#accounts">Accounts</a><a href="#acceptable">Acceptable use</a><a href="#store">Store</a><a href="#availability">Availability</a><a href="#liability">Liability</a><a href="#law">Governing law</a></nav>
    <article className={styles.content}>
      <section id="agreement"><h2>1. Agreement to these terms</h2><p>By using this website, you agree to these Terms of Use and acknowledge our <Link href="/privacy">Privacy Policy</Link> and <Link href="/cookies">Cookie Policy</Link>. If you do not agree, please do not use the website or create an account.</p><p>PENREC Music Group is an independent music project founded and operated by Darren Penman in the United Kingdom.</p></section>
      <section id="content"><h2>2. Music, artwork and website content</h2><p>The music, recordings, lyrics, artist names, biographies, photographs, artwork, logos, graphics, text, design and software made available through PENREC are owned by or licensed to PENREC Music Group and are protected by copyright and other applicable rights.</p><p>You may access and listen to material for your personal, non-commercial enjoyment. Unless we give written permission, you must not copy, download, redistribute, sell, publicly perform, broadcast, modify, scrape, train systems on, or create derivative works from PENREC content.</p><p>Nothing on the website transfers ownership or grants a commercial licence. Licensing and professional-use enquiries should be made through our <Link href="/contact">contact page</Link>.</p></section>
      <section id="accounts"><h2>3. Accounts</h2><p>You must provide accurate information, keep your sign-in details secure and notify us if you believe your account has been compromised. You are responsible for activity carried out through your account unless caused by our failure to use reasonable care.</p><p>You must not create accounts using another person’s identity, interfere with another user’s account or use automated methods to create accounts. We may restrict or suspend an account where reasonably necessary to protect users, PENREC or the website.</p></section>
      <section id="acceptable"><h2>4. Acceptable use</h2><p>You must not:</p><ul><li>use the website unlawfully, fraudulently or to harm another person;</li><li>attempt to bypass access controls, probe security or disrupt the service;</li><li>introduce malware or other damaging code;</li><li>harvest personal information or send unsolicited communications;</li><li>misrepresent an association with PENREC or any PENREC artist; or</li><li>use the contact form to submit abusive, defamatory, infringing or illegal material.</li></ul></section>
      <section id="store"><h2>5. Store and future purchases</h2><p>The PENREC Store is currently a catalogue preview and is not yet accepting checkout payments. Product descriptions, availability indications and proposed prices shown before commerce launches do not constitute an offer capable of acceptance.</p><p>Before transactions open, we will provide the additional purchase, delivery, cancellation, returns and digital-content terms required for the products offered. Those purchase terms will supplement these website terms and will not limit rights provided by UK consumer law.</p></section>
      <section id="links"><h2>6. External links and services</h2><p>The website may link to third-party websites or services. Those services operate under their own terms and privacy notices. A link does not mean that PENREC controls or endorses everything available through the external service.</p></section>
      <section id="availability"><h2>7. Availability and changes</h2><p>We aim to keep the website and player available and accurate, but we do not promise uninterrupted or error-free access. Music, features and content may be updated, removed or temporarily unavailable for maintenance, security, rights-management or operational reasons.</p><p>We may amend these terms when PENREC services or the law changes. Material changes will apply from the date shown on the updated page and will not retrospectively remove accrued legal rights.</p></section>
      <section id="liability"><h2>8. Responsibility and liability</h2><p>Nothing in these terms excludes or limits liability where doing so would be unlawful, including liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, or your statutory consumer rights.</p><p>The website is provided primarily for personal and general informational use. To the extent permitted by law, PENREC is not responsible for losses that were not reasonably foreseeable, losses caused by events outside our reasonable control, or business losses arising from consumer use of the website.</p></section>
      <section id="ending"><h2>9. Ending access</h2><p>You may stop using the website at any time. You can ask us to close your account through the <Link href="/contact">contact page</Link>. We may suspend or end access where these terms are seriously or repeatedly breached, or where necessary for security or legal compliance.</p></section>
      <section id="law"><h2>10. Governing law</h2><p>These terms are governed by the laws of England and Wales. If you are a consumer living elsewhere in the United Kingdom, you retain any mandatory protections and may bring proceedings in the courts available to you under applicable law.</p><p>Questions about these terms can be sent through the <Link href="/contact">PENREC contact page</Link>.</p></section>
    </article>
  </div>
</main>}
