import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal.module.css";

export const metadata: Metadata = { title: "Cookie Policy | PENREC Music Group", description: "How PENREC Music Group uses cookies and browser storage." };

export default function CookiesPage(){return <main id="content" className={styles.page}>
  <header className={`shell ${styles.hero}`}><p className="eyebrow">Legal / Last updated 4 August 2026</p><h1>Cookie <em>policy.</em></h1><p>A clear explanation of the cookies and browser-storage technologies used by the PENREC website.</p></header>
  <div className={`shell ${styles.layout}`}>
    <nav className={styles.nav} aria-label="Cookie policy sections"><a href="#meaning">What they are</a><a href="#use">What we use</a><a href="#storage">Browser storage</a><a href="#consent">Consent</a><a href="#control">Your controls</a><a href="#changes">Changes</a></nav>
    <article className={styles.content}>
      <section id="meaning"><h2>1. What cookies and local storage are</h2><p>Cookies are small pieces of data stored by a website in your browser. Local storage is a related browser technology that allows a site to retain settings or content on a device. Some are essential for requested features to work; others can be used for analytics or advertising.</p></section>
      <section id="use"><h2>2. Cookies PENREC currently uses</h2><p>PENREC currently uses only essential authentication cookies. They are set after a user signs in and are not used for advertising or behavioural analytics.</p><table className={styles.table}><thead><tr><th>Name</th><th>Purpose</th><th>Typical duration</th></tr></thead><tbody><tr><td><strong>penrec_access_token</strong></td><td>Authenticates a signed-in account and protects access to account or staff features.</td><td>Approximately one hour, unless refreshed or removed earlier</td></tr><tr><td><strong>penrec_refresh_token</strong></td><td>Allows the service to securely renew a signed-in session.</td><td>Up to 30 days, or until sign-out</td></tr></tbody></table><p>These cookies are HTTP-only, which means website scripts cannot read them. In production they are also transmitted securely and use SameSite protections.</p></section>
      <section id="storage"><h2>3. Functional browser storage</h2><p>The PENREC music player stores your chosen volume level under <strong>penrec_player_volume</strong> so it can be restored on your next visit. The current playback queue otherwise remains in application memory while a page session is active.</p><p>PENREC Studio uses local storage on authorised staff devices to retain draft editorial, homepage, release and media-management settings. This storage supports functionality deliberately requested by the user. None of this storage is used to track visitors across websites or for advertising analytics.</p></section>
      <section id="consent"><h2>4. Why there is no advertising-cookie banner</h2><div className={styles.callout}><p>The current PENREC website does not set advertising or non-essential analytics cookies.</p></div><p>Essential cookies used to provide a sign-in service requested by the user do not require opt-in consent under current UK rules, although we must still explain them. If PENREC later introduces analytics, embedded media, personalisation or advertising technologies that require consent, they will remain disabled until an appropriate choice has been made.</p></section>
      <section id="control"><h2>5. Managing cookies and storage</h2><p>You can use your browser settings to view, block or delete cookies and local storage. Blocking essential authentication cookies will prevent account sign-in and protected Studio functions from working. Signing out removes the active PENREC authentication cookies.</p><p>Instructions differ by browser and device; consult your browser’s privacy or site-data settings for details.</p></section>
      <section id="third"><h2>6. Third-party websites</h2><p>Links to music platforms or other external websites may take you to services that use their own cookies. Their cookie practices are controlled by those organisations and covered by their own notices.</p></section>
      <section id="changes"><h2>7. Changes and contact</h2><p>We will update this policy if the technologies used by PENREC change. The latest update date appears at the top of this page. For questions, use the <Link href="/contact">PENREC contact page</Link>. Information about personal data is available in our <Link href="/privacy">Privacy Policy</Link>.</p></section>
    </article>
  </div>
</main>}
